spring:
  datasource:
    url: ${DB_URL}
    username: ${RDS_USER_NAME}
    password: ${RDS_USER_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${DEV_MONGODB_URI}
      database: ${DEV_MONGODB_DB_NAME}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    aws:
      credentials:
        access-key: ${DEV_AWS_ACCESS_KEY}
        secret-key: ${DEV_AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
auth:
  oauth2:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    oauth-iss: ${OAUTH_ISS}
    oauth-server-token-uri: ${OAUTH_SERVER_TOKEN_URI}
    oauth-jwk-set-uri: ${OAUTH_JWK_SET_URI}
    oauth-server-user-info-uri: ${OAUTH_SERVER_USER_INFO_URI}
    kakao:
      kakao_grant_type: ${KAKAO_GRANT_TYPE}
      kakao_grant_type_name: ${KAKAO_GRANT_TYPE_NAME}

myapp:
  sqs:
    queue-name: ${DEV_AWS_SQS_QUEUE_NAME}
    queue-url: ${DEV_AWS_SQS_QUEUE_URL}
    messageDelaySecs: 0