spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${MONGODB_LOCAL_DB_URL}
      database: ${MONGODB_DATABASE}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    aws:
      credentials:
        access-key: ${LOCAL_AWS_ACCESS_KEY}
        secret-key: ${LOCAL_AWS_SECRET_KEY}
      region:
        static: ap-northeast-2

myapp:
  sqs:
    queue-name: ${SQS_QUEUE_NAME}
    queue-url: ${SQS_QUEUE_URL}
    messageDelaySecs : 0
