spring:
  profiles:
    active: local
  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

notion:
  token: ${NOTION_API_TOKEN}
  database_id: ${NOTION_DATABASE_ID}
  version: ${NOTION_VERSION}

slack:
  webhook_url: ${SLACK_WEBHOOK_URL}
